# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'MindTheTime' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MindTheTime
  # please note that RxFirebase also links Firebase/Core resulting in link errors.
  # I temporarely solved it by only including the RxFirebase pod.
  #
  # pod 'Firebase/Core'
  pod 'RxFirebase', path: '~/dev/MindTheTime/RxFirebase/RxFirebase.podspec'

  target 'MindTheTimeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MindTheTimeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
